dist: trusty
sudo: require
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - sourceline: 'ppa:george-edison55/cmake-3.x''
    packages:
      - libboost-all-dev
      - cmake
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
